# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- lint
- test
variables:
  POSTGRES_USER: stig_a_view
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: test_stig_a_view
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: redis://redis:6379/0
flake8:
  stage: lint
  image: python:3.9-alpine
  before_script:
  - pip install -q flake8
  script:
  - flake8
pytest:
  tags:
  - docker
  stage: test
  image: python:3.9
  services:
  - postgres:13.2
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
  before_script:
  - pip install -r requirements/local.txt
  script:
  - pytest
include:
- template: Auto-DevOps.gitlab-ci.yml
