# Generated by Django 3.1.13 on 2021-10-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cci_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Srg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srg_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_id', models.PositiveIntegerField()),
                ('disa_stig_id', models.CharField(max_length=50)),
                ('severity', models.IntegerField(choices=[(0, 'High'), (1, 'medium'), (2, 'low')], default=0)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('fix_text', models.TextField()),
                ('fix', models.TextField()),
                ('check_content', models.TextField()),
                ('cci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cci')),
                ('srg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.srg')),
                ('stig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stig')),
            ],
        ),
    ]
