# Generated by Django 3.1.13 on 2022-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='srg',
            name='title',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='control',
            name='severity',
            field=models.IntegerField(choices=[(0, 'high'), (1, 'medium'), (2, 'low')], default=0),
        ),
    ]
